name: AxTrade
version: '${project.version}'
main: com.artillexstudios.axtrade.AxTrade
api-version: '1.18'
folia-supported: true

softdepend:
  - AxQuestBoard
  - CoinsEngine
  - Kingdoms
  - PlaceholderAPI
  - PlayerPoints
  - RivalHarvesterHoes
  - RoyaleEconomy
  - SuperMobCoins
  - TheOnly-MobCoins
  - TokenManager
  - UltraEconomy